// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cyber-studio-home/CommandCenter.tsx": () => import("../components/mockups/cyber-studio-home/CommandCenter.tsx"),
  "./components/mockups/cyber-studio-home/CyberpunkSlate.tsx": () => import("../components/mockups/cyber-studio-home/CyberpunkSlate.tsx"),
  "./components/mockups/cyber-studio-home/FigmaDark.tsx": () => import("../components/mockups/cyber-studio-home/FigmaDark.tsx")
};
